from pathlib import Path
BASE = Path("C:/Users/13065/Documents/GitHub/queering-geographies")

TXT_PARSER_IN = BASE / "fugue_blocks_2011_round1.json"
TXT_PARSER_OUT = BASE / "fugue_2011-2016-202

TXT_PARSER_CLEAN_IN = TXT_PARSER_OUT
TXT_PARSER_CLEAN_OUT = TXT_PARSER_CLEAN_IN WHATEVER

SPACY_PARSER_IN = TXT_PARSER_CLEAN_OUT
SPACY_PARSER_OUT = SPACY_PARSER_IN WHATEVER

GEOCODER_IN = SPACY_PARSER_OUT
GEOCODER_OUT = GEOCODER_IN WHATEVER